### ISSUE TITLE
Active development?

### ISSUE THREAD

**Issue by trks1970** [spring-projects/spring-statemachine#1081]
Hi!

Is the project being actively developed?
We are just starting a project (Spring3) and are evaluating if spring-state-machine would be an option for us.
(Or if we take the burden of moving it to spring3/Java 17)

**Comment by mehmetsalgar** [comment]
Ok, I have no direct affiliation with Spring State Machine development or with the company, so please take what I say here with certain grain of salt.

My feeling about SSM, it is now a maintenance project and too many activities occurring but beside that, if you are interested using State Machine paradigm, you should really consider SSM fits to business problem.

SSM is great for ex, controlling lifecycle of an automat, like STARTING, STARTED, SHUTTNGDOWN, ERROR_MODE, MAINTENANCE, etc, but in my opinion it is not suited for modelling millions of shopping charts, hotel reservations, etc because I think it's persistence model is too naive and has concept for business model or state machine model evaluation which will certainly happen any real life scenario.

If you are planning to use model a similar to the automat mentioned above, SSM is great for it and do it.

If you are planning to have millions of instance of the state machine, I strongly advice you to evaluate other frameworks.

I have a blog [post](https://mehmetsalgar.wordpress.com/2022/04/18/a-model-driven-event-sourced-cloud-ready-application-with-akka-finite-state-machine-using-kafka-cassandra-and-elasticsearch/) exactly discussing this points may be it can help you.

**Comment by XhstormR** [comment]
So it is currently not compatible with Spring Boot 3?

**Comment by andreas-schilling** [comment]
PR has been merged, but no release yet: https://github.com/spring-projects/spring-statemachine/pull/1104

**Comment by jvalkeal** [comment]
Apologies that it has taken too much time to start work on 4.x. We try to go through this process relatively quickly and get supported version for boot 3 out. I'd recommend to follow updates to `4.x.x` milestones.
