### ISSUE TITLE
Support for UML Sub State Machines

### ISSUE THREAD

**Issue by mehmetsalgar** [spring-projects/spring-statemachine#121]
For a while ago, I created another entry about adapting a feasibility project (https://mehmetsalgar.wordpress.com/2014/05/22/extremely-ajaxified-web-application-with-spring-webflow-primefaces-and-state-machines) that I previously developed to the Spring State Machine.

Actually adaptation run quite well until this point that I will mention here, which will probably will be an enhancement request.

I used in my feasibility project the concept of Nested State Machines (or UML Sub Machines in UML notation) to control the state explosion phenomena. I previously asked here that spring statemachine does support this concept or not. It seems Spring State Machine support the concept of nested states but not necessarily the concept of the nested state machines (discussion can be found here: https://mehmetsalgar.wordpress.com/2014/05/22/extremely-ajaxified-web-application-with-spring-webflow-primefaces-and-state-machines/#nested_sm).

It is pointed in this example how to build a nested state machine, 'http://docs.spring.io/spring-statemachine/docs/1.0.0.RELEASE/reference/htmlsingle/#statemachine-examples-showcase', but this is actually nested states.

I have the feeling Spring State Machine tries to stay real close to the concepts of UML State Machines but it seems there is a deviation here.

What I want to achieve here can be seen in the following 2 pictures.

https://mehmetsalgar.wordpress.com/?attachment_id=476
https://mehmetsalgar.files.wordpress.com/2013/11/picture_4.gif

this example contains TechDemoSM State Machine having as a Sub State Machine (nested State Machine) CustomerSearchSM, in general, it is similar to the concept of nested states, the problem arise when I try to configure these 2 State Machines over EnumStateMachineConfigurerAdapter interface.

What I need looks like following

for TechDemoSM

@Override
public void configure(
			StateMachineStateConfigurer<TechDemoSM_StateEnumerationImpl, TechDemoSM_EventEnumerationImpl> states) throws Exception {
   states.withStates()
.initial(TechDemoSM_StateEnumerationImpl.CUSTOMERSEARCH_PROCESSING,
						initialStateTechDemoSMAction())
.state(TechDemoSM_StateEnumerationImpl.CUSTOMERSEARCH_PROCESSING)
.submachine(CustomerSearchSM);

for CustomerSearchSM

@Override
public void configure(
			StateMachineStateConfigurer<CustomerSearchSM_StateEnumerationImpl, CustomerSearchSM_EventEnumerationImpl> states) throws Exception {
    states.withStates()
    .initial(CustomerSearchSM_StateEnumerationImpl.WAITING_CUSTOMERSEARCH_START,
						initialStateCustomerSearchSMAction())
				.states(EnumSet.allOf(CustomerSearchSM_StateEnumerationImpl.class));

I can't find a mechanism that help me create this configuration.

Of course, I can try to model everything a single State Machine but when the number use cases and complexity of the application increase (which I discuss here: https://mehmetsalgar.wordpress.com/2014/05/22/extremely-ajaxified-web-application-with-spring-webflow-primefaces-and-state-machines/#stateexplosion), maintenance of the application and the state machines will be become increasingly difficult if I put everything inside of one State Machine.

So what I like to ask is there a way to configure Spring State Machine this way? If not, what is the realistic chance that get a feature for Nested State Machines?

**Comment by jvalkeal** [comment]
I didn't understand from your blog how nested machines work in your model. Or if being more clear, how they operate together? I've always understood that nested machines, as whole, simply provide similar functionality as you get from object orientated programming(class hierarchy) where each machine has its own transitions and then events can be processed(accepted) by different nested machines, thus allowing you to provide common functionality on a super-machine if sub-machine doesn't don't want to process an event. If you have some other ways to use sub-machines then please show me the light because I've clearly missed something ;)

Back to the actual response, you're right and wrong.

Right in terms of that we don't currently support adding external state machine as a submachine state.

Wrong in terms of that we only have a concept of nested states. When state machine builder detects a presence of a nested state, state is created as `StateMachineState` which encapsulates a full state machine(different instance than parent machine). Normal state(i.e. based on String or Enum) is created as `ObjectState`. Similarly once we have multiple initial states we make an assumption that multiple regions are present thus causing use of `RegionState`.

I just pushed a change to samples logging to show on which source state an internal transition is executed. I realized that use of nested states wasn't very clearly explained. I'm copying new stuff from docs to below:

```
sm>sm variables
No variables

sm>sm start
Init foo to 0
Entry state S0
Entry state S1
Entry state S11
State machine started

sm>sm variables
foo=0

sm>sm event H
Internal transition source=S1
Event H send

sm>sm variables
foo=0

sm>sm event C
Exit state S11
Exit state S1
Entry state S2
Entry state S21
Entry state S211
Event C send

sm>sm variables
foo=0

sm>sm event H
Switch foo to 1
Internal transition source=S0
Event H send

sm>sm variables
foo=1

sm>sm event H
Switch foo to 0
Internal transition source=S2
Event H send

sm>sm variables
foo=0
```

Event `H` is defined with a three different states(`S0`, `S1` and `S2`). Transition is added to a state machine who owns that particular source state.

```
.withInternal()
	.source(States.S0).event(Events.H)
	.guard(foo0Guard())
	.action(fooAction())
	.and()
.withInternal()
	.source(States.S2).event(Events.H)
	.guard(foo1Guard())
	.action(fooAction())
	.and()
.withInternal()
	.source(States.S1).event(Events.H)
	.and()
```

From above example when event `H` is send you can clearly see how event is processed with a different state machine depending on a value of a extended state variable `foo`. Transition is guarded by a `Guard` and event is first offered to deepest state(state machine) and then worked towards super-states(parent machines) until one accepts that event.

Having said that, I originally played with an idea that with configurer interfaces you could attach a state machine(think I event had `submachine()` method there) but then went with other route. I think I had some trouble getting that concept working. Well you have played with state machines and probably know that once you step outside of a simple flat one level machine, things get very complicated with the implementation.

I'm definitely open for discussion for stuff like this. UML spec is very *vague* on some concepts and don't really provide any examples how machine should work. It leaves a lot of *stuff* to the implementation to decide how things should work which is natural because spec only defines UML diagram. With a proper state machine spec it would have a test cases how machine would work on specific cases.

**Comment by mehmetsalgar** [comment]
In general, it is exactly what you mentioned, I explain this extensively under the topic "Ultimative Hook Pattern", which is actually nothing more then event model of the "Windows Operating System".

Lets say we have 2 State Machines, StateMachine_A and StateMachine_B, one of StateMachine_A contains a State_A which has a StateMachine_B as submachine.

So lets say StateMachine_A gets Event_A and it is already in State_A, then first thing that StateMachine_A asks to StateMachine_B can handle this Event_A or not. If StateMachine_B has a transition on this current State to handle this Event_A it will be processed at StateMachine_B otherwise it will delegate back to StateMachine_A to handle.

So more concrete example, like the one in the blog, lets say I want to build an error handling, now if every State in the StateMachine_B can cause an error then every state in the StateMachine_B must have a transition to the STATE_ERROR, when the number of states increase that will make StateMachine_B extremely complex.

Better solution would be, not the handle this transition in StateMachine_B but include StateMachine_B into the StateMachine_A as a submachine to State_A which can have a transition to STATE_ERROR and which can deal for every possible State of the StateMachineB.

Like Windows Operating System, which first ask to specialized Window to handle an event and if it can't handle it will delegate to general EventHandler.

It is the same principle.

Now as I said, the way your Nested States (StateMachineState) handles the thing, it is nearly the same way, only notation is different then UML Submachine notation, which makes hard if you design your StateMachine with UML Diagram to convert to Spring State Machine Configuration model.

I can do it, but as you most certainly know %90 of software development conquering and dividing, instead of having clean designed several State Machines if I follow the UML Model with your model I will have an one big complex State Machine.

**Comment by jvalkeal** [comment]
Yes you certainly have a valid point here! If being totally honest I have had this ticking annoyance that once you make complex configuration it is relatively difficult to see the big picture once configuration statement doesn't fit in one page or screen. We were on a same page and what you wrote in that section makes sense indeed.

Lemmy try to think how we could provide what you need. Most of the event processing(actual event task scheduling) is actually done on a top-level machine to guarantee run-to-completion model, while only orthogonal regions can do event processing individually(parallel). This is the biggest trouble we're going to face with this when we attach external machine into other machine as a state(because we still need to guarantee run-to-completion). But I suppose that is my problem then *grin* :)

Good thing is that most of the facilities are already in place because we have real separate machine instances handling nested states so if we're lucky we're not that far away. Otherwise we'd need a major re-write which would be a real PITA.

I could try to do some prototyping to see where we are and how extended config model would look like.

**Comment by mehmetsalgar** [comment]
If you look to the blog, you see that I wrote my state machine implementation because I could not find an implementation that fit my needs.

It is nearly no way complex as spring-statemachine but when I encountered this problem, I decided it is better to bypass the event-queue mechanism for the sub state machine.

As you said parent state machine is already controlling the event queue and nested machine has no other means to receive events from the outside world so for the submachine, I bypassed the event queue and dispatch the events directly.

**Comment by mehmetsalgar** [comment]
I was playing little bit SubMachine to figure out how to configure those with spring-statemachine when the necessary changes for it implemented.

There is one point that is bugging me...

I find it really elegant that state machine can be configured with the enumerations but what will happen with the sub machines.

Lets say I have a STATE_MACHINE_A and I configured with the following snippet.


*********************************************************************************************
@Override
public void configure(
			StateMachineTransitionConfigurer<CustomerSearchSM_StateEnumerationImpl, CustomerSearchSM_EventEnumerationImpl> transitions)
					throws Exception {
	transitions
	.withExternal().source(STATE_MACHINE_A_StateEnumeration.INITIAL)
.target(STATE_MACHINE_A_StateEnumeration.STATE_A)
.event(STATE_MACHINE_A_EventEnumeration.onStartSearch)
.action(action())

***********************************************************************************************

and lets say STATE_A has sub machine STATE_MACHINE_B, now if I want to send an event to STATE_MACHINE_B I have to use something like this when STATE_MACHINE_A is in STATE_A.

Message<STATE_MACHINE_B_EventEnumeration> message = MessageBuilder.withPayload(STATE_MACHINE_B_EventEnumeration.onOrderSearchRunning).setHeader("foo", 5).setHeader("goo", 11).build();

STATE_MACHINE_A.sendEvent(message); 

while for the message has to go STATE_MACHINE_B I have to use STATE_MACHINE_B_EventEnumeration but I should send the event to STATE_MACHINE_A with 'STATE_MACHINE_A.sendEvent(message)'

I am even not sure this will work or not but sure it does not look elegant.

The ideal would be that I can inherit STATE_MACHINE_A_EventEnumeration from STATE_MACHINE_B_EventEnumeration so it will know the Event of the STATE_MACHINE_B but unfortunately Java does not allow inheritance from enumerations.

My be it is better to let state machines configured from interfaces with constant definitions, so inheritance can be used.

**Comment by mehmetsalgar** [comment]
Is there a timetable for the solution of this Issue? Like next 3 months, 6 months...?

There are several projects that I am involved which I like to recommend the use of Spring State Machine but without knowing the timetable for the resolving of this Issue I really can't.

It is work in progress or is it on ice at the moment.

**Comment by jvalkeal** [comment]
Yes it is work in progress as I also have need for this feature. I put it for 1.2.0 for now and we'll see how big changes it needs.

**Comment by jvalkeal** [comment]
Paging @mehmetsalgar. I created a PR(for review) #236 if you want to poke around and add comments. This surely is a bit complex but this is a first take on this issue. We may need few iterations to make it clean.

**Comment by mehmetsalgar** [comment]
Hi, you catch me in the middle of my vacation and I just saw this. I will make the peer review as quickly as possible.

**Comment by jvalkeal** [comment]
Sure, it's already merged into master. Until 1.2.x is released we can change and tune things as much as we need.
