### ISSUE TITLE
Clarification in docs about states and why is there no method StateMachine.setState?

### ISSUE THREAD

**Issue by pgifford** [spring-projects/spring-statemachine#127]
I'm not a state machine guru so perhaps some clarification in the docs might be helpful to others like me.  It is not clear to me why there is no method `StateMachine.setState(State)` since `StateMachine` has a `getState()` method.  `getState()` comes from `Region` so maybe the right question to ask is, why doesn't `Region` have a `setState(State)` method?

I think I understand that the purpose of the code to set the state of state machine in the [Persist recipe](https://github.com/spring-projects/spring-statemachine/blob/master/spring-statemachine-recipes/src/main/java/org/springframework/statemachine/recipes/persist/PersistStateMachineHandler.java) is to set the state in every possible region but if regions are orthogonal then how can one `State` be used for every `Region`?

```java
stateMachine.stop();
List<StateMachineAccess<String, String>> withAllRegions = stateMachine.getStateMachineAccessor().withAllRegions();
for (StateMachineAccess<String, String> a : withAllRegions) {
	a.resetStateMachine(new DefaultStateMachineContext<String, String>(state, null, null, null));
}
stateMachine.start();
```

It's probably clear by now that I'm really not sure what I'm talking about but in case it's not...

Some additional clarification might be helpful in the docs to explain why interface [`State`](http://docs.spring.io/spring-statemachine/docs/1.0.1.RELEASE/api/org/springframework/statemachine/state/State.html) is parameterized over both state S (the type of state) and event E (the type of event). It seems logical that a `State` would necessarily be paramterized over the type of state (with a corresponding `getId()` that returns the type of state) but I couldn't even hazard a guess as to why the type of event is required.

My code works but I don't understand everything it's doing and that makes me nervous.  I'm not very experienced with state machines so perhaps my questions are basic but I suspect this library will attract other developers who also lack experience with state machines, thus this request for more detail in the documentation.

A few words about my specific use case, for context: we're using Spring Statemachine in a webapp and generally following the Persist recipe.  However, we're using a state machine factory and creating a state machine each time a state is loaded from the database.  Speaking of `StateMachineFactory`, it would be helpful if it had a method `getStateMachine(State, ExtendedState)`, and thus be able to churn out state machines in the desired state.

**Comment by mehmetsalgar** [comment]
Ok, I have no organic connection to this project but while you are asking a generic question about state machine, I will try to answer.

Changing internal state of a machine can only occur via transitions and event corresponding to those transitions. You can't arbitrarily set States to the State Machines.

Otherwise think this scenario, you are at STATE_A and you received an EVENT_A which leads to TRANSITION_A when this event precessing you set the State of the State Machine to STATE_B. What should the State Machine do now?

It was in the middle of processing EVENT_A for STATE_A and now it is in STATE_B. State Machine can't deal with such a scenario, everything in State Machine must be deterministic, that is the reason we use State Machines, to bring order to the chaos but what you define is the chaos we want to get away from it.

I think Spring State Machine is capable of deserialize itself via Java deserialization mechanism you have to look there and customize there to be able to deserialize from Database.

**Comment by pgifford** [comment]
Thank you for the explanation.  It seems I wasn't clear in what I wrote.  I'm not looking to change the state of an existing machine to a different state and thus subvert the operation of a machine.  Let's say that I know that state machine SM123 is in state ABC.  I persist that state because at some point SM123 will go away (I restart the server, for example).  I know how to make another SM123 - I need to set it to state ABC so on restart it's in the same state as it was when the server was shut down.

**Comment by jvalkeal** [comment]
Good questions indeed. I've been thinking to write a new section to ref docs which would give more "developer" level information.

Why no `setState(State)` method? As already mentioned above, state machine cannot have public api setting a state because state change need to happen internally. That's why I created `resetStateMachine()` which only works when state machine is stopped.

Why `State<S, E>` has two parameterized types? With a simple one level flat state machine, implementation could simply use object or something similar. In our implementation `State` is much more than a representation of a state identifier(what you'd write into a state chart). There are implementations like `ObjectState`, `StateMachineState` and `RegionState` which brings all those sophisticated features like orthogonal regions and nested states. If state is a nested state it has its own nested state machine, thus needs to be aware of event type("E").

Resetting a state machine is a relatively complex operation and gets more complex when you throw regions and nested states in to the picture.

If your state machine contains nested states then resetting particular state to all machines will in theory only touch one machine because we don't support same states in different nested states. There is a #121 to relax this requirement. Also because nested state configuration is immutable, when we reset deepest state, we already know all active super-states.

With regions this trick doesn't work anymore and then `StateMachineContext` should have info about childs. That's easier to understand if you see reset code for regions https://github.com/spring-projects/spring-statemachine/blob/master/spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java#L505

`PersistStateMachineHandler` recipe is really meant for one level flat machine but I should revisit it provide better support for more complex machines.

**Comment by pgifford** [comment]
@jvalkeal, thank you for the thorough clarification. An implementation of a single level, non-nested state machine would be useful to those, like me, are just cutting their teeth on state machines and aren't yet ready for the sophisticated features (orthogonal regions and nested states).  I suspect I'll need those features but don't know enough to know that I need them yet...I've been working on getting the most basic of state machines running (which I've done).

Clearly I don't know what I don't know.  It's not your job to teach a course in state machines so I'm very grateful for your patience!

**Comment by jvalkeal** [comment]
Closing this for now in favour of #158. Linking to it so that we don't forget stuff in this issue.
