### ISSUE TITLE
Pass parameters to guards methods

### ISSUE THREAD

**Issue by vakoroteev** [spring-projects/spring-statemachine#159]
I'm interesting in a little bit strange behaviour of guards methods. It's part of my configuration:
```java
.withChoice()
                .source(BET_MATCHED)
                .first(ONE_MATCHED, matchedCntGuard(1))
                .then(TWO_MATCHED, matchedCntGuard(2))
                .then(NO_MATCHED, matchedCntGuard(0))
                .last(ERROR_STATE)
...
.and()
.withChoice()
                 .source(SAVE_STATE)
                 .first(TWO_MATCHED, matchedCntGuard(2))
                 .last(ONE_MATCHED)
            
    @Bean
    public Guard<BfStates, BfEvents> matchedCntGuard(int cnt) {
        return context -> compareVariableGuardHelper(cnt, MATCHED_CNT, context);
    }
```
At first everything was fine, all tests passed. But later I started to notice a strange thing. Variable ```cnt``` at ```matchedCntGuard``` always equals to 1 even if guard invokes from ```SAVE_STATE```. If I change order of choices in ```BET_MATCHED``` state, for example move ```NO_MATCHED``` and ```matchedCntGuard(0)``` to ```first```, ```cnt``` equals to 0. So I concluded that variables in guards methods are constant and equals to value of first occurance of guard in config.

Later in documenation I found example with ```FooGuard``` that implements standard Guard. So I think that it's impossible pass parameters to guard functions and such behaviour is not a bug, but something else.

However, I think that such behaviour should be describe in documenation of project.
Also I was wondering do you plan to add the functionality of the passing parameters to a guard?

**Comment by jvalkeal** [comment]
So I think you simply got burned by how spring beans works with javaconfig. If within this `@Configuration` class you refer to same method `matchedCntGuard` regardless what is a parameter value for `cnt`, spring will cache bean reference and use it. If you want to use multiple _instances_ of `matchedCntGuard`, remove `@Bean` from it. This is not state machine specific behaviour, it's just a way spring javaconfig works. You always get instance with `1` because that's requested first and bean is created and all other references to it will get same instance.

If you are using same `Guard` in multiple places and `Guard` class itself is stateless and thread-safe, then it makes sense to create it as a bean and share it. In your case it's not stateless so you can't share same instance. Makes sense? Lemmy know if this helps to fix your issue :)

**Comment by vakoroteev** [comment]
Thanks for the clarification =)

**Comment by jvalkeal** [comment]
@vakoroteev yeah, I'll try to remember to add a short `note` to docs about this(you said it so next guy is probably gonna have same trouble/issue). I think every spring dev will get burned by this when javaconfig is used like this way. Method calls within `@Configuration` classes are actually kinda auto-wired so time to time with some spring javaconfig examples methods are called with nulls. Think you had a same kind of moment than I had in my early days of learning spring, 'what a hell just happened' :)
