### ISSUE TITLE
Question: How to set a state to the state machine

### ISSUE THREAD

**Issue by louxl** [spring-projects/spring-statemachine#167]
Hello,

We are trying to adapt spring-statemachine as our foundation framework to support and drive order(for a E-Businese application) state transition. But now we need some help to onboard. 

Our order info (including state and context) are persisted in a MySQL Database. To simplify, we assume there are only three state for an order -- "new" / "paid" / "dilivered", and the life cycle of an order could be a couple days. 

After a quick go through of the document, I have no luck to spot an approach to initialize the context and the state in the middle of the order lifecycle. For example, when I fetch a "paid" order from database, how could I correctly set the state of the order to the state-machine?

Any help would be appreciated. Thanks in advanced!

**Comment by jvalkeal** [comment]
Have you checked what `persist` sample and recipe can do? These basically work around a concept of resetting a statemachine. This reset feature is hidden from a public `StateMachine` api because it'd be a little awkward feature on that level, but it is available from a `StateMachineAccessor` api's.

Things are little limited with 1.0.x serie but with 1.1.x things are going to be easier to use. In fact I just pushed a https://github.com/spring-projects/spring-statemachine/commit/294430c9fb8c5244be9bcf3b6c39e1e826d91057 to master which is using redis as a persist store and resets machine from there. Existing `persist` sample is actually using embedded database to reset state manually so kinda relates what you're trying to do.

**Comment by louxl** [comment]
thanks a lot, @jvalkeal 
Let me have a try.

**Comment by jvalkeal** [comment]
closing for now, ping back if there's other issues.

**Comment by subrat1985** [comment]
Suppose I have three states-NEW,VALIDATE,DEBIT and my request failed at VLAIDATE state them am putting request to Kafka topic ,Trying to process that request from VALIDATE state is it possible to process a  request middle of the any state .
