### ISSUE TITLE
Using SSM in a web application (non-distributed) with multiple requests support

### ISSUE THREAD

**Issue by sengopal** [spring-projects/spring-statemachine#170]
_N00bie here. Apologies if my understanding is incorrect._

I am using SSM for a web application which performs something similar to the Persist recipe. However, since the StateMachine object is singular, I am confused as to how would multiple parallel requests work. 
Should i be creating a new StateMachine object per request and trigger the event or is there a simpler means to use one instance of the SM, but ensure that each request has its own threadlocal copy of data such as MessageHeaders, currentState etc.,

Can you please clarify?

**Comment by jvalkeal** [comment]
For 1.0.x things are a bit limited because you'd need to control all that yourself(but yes you on a right track). For 1.1.x things around web and scopes are going to be much better implemented in terms of usability. New sample http://docs.spring.io/spring-statemachine/docs/1.1.0.M1/reference/htmlsingle/#statemachine-examples-eventservice was done exactly for this use case and we made a lot of enhancements for all this not to be so difficult from user perspective.

Essentially that sample will will persist(using redis) state machine per user and request and reuse pool of state machines to avoid expensive instantiation(thought instantiation per request is also possible). For 1.1.0.M2 we're doing further enhancements for scoping and especially `spring-session`.

**Comment by sengopal** [comment]
Ah. Thanks so much.That explains a lot. Is the 1.1.X release planned soon.

**Comment by jvalkeal** [comment]
Target is around April/May.

**Comment by sengopal** [comment]
Just an update. We had to go with squirrel (https://github.com/hekailiang/squirrel) as it satisfies our usecase creating a new State machine object and uses ThreadLocalContext.
