### ISSUE TITLE
Final state is lost when exiting from a submachine

### ISSUE THREAD

**Issue by aldib** [spring-projects/spring-statemachine#190]
When issuing a transition from a submachine which target is a final state, `StateMachine.getState()` returns null. In same cases it throws a NPE. I attached test cases for both scenario.

[spring-statemachine-bug.zip](https://github.com/spring-projects/spring-statemachine/files/186821/spring-statemachine-bug.zip)

**Comment by jvalkeal** [comment]
Behaviour of a final state is quite vague what comes for the uml spec. Currently what happens is that once `END` state is entered, machine is considered `complete` and it stops itself, which consequently clears everything including current state.

Question is if machine is not running, should it have a state anymore? Should we keep the state when machine is stopped? This may be a bit awkward if machine is stopped and its last state was not a final state.

From specs:
```
[1] A final state cannot have any outgoing transitions.
[2] A final state cannot have regions.
[3] A final state cannot reference a submachine.
[4] A final state has no entry behavior.
[5] A final state has no exit behavior.
[6] A final state has no state (doActivity) behavior.
```
Think we also need to add check to a config model so that user would not try to add any of above stuff, thought point 6 might indicate that while machine is complete, state might actually exist. This illegal behaviour might i.e. be a timer which tries to do internal transition on an end state.

What do you think?

**Comment by jvalkeal** [comment]
scrap my comment, I was too focused on a flat level machine and returning null for substates or regions is plain wrong. I'll get this fixed.

**Comment by aldib** [comment]
Hi,
I find that technical specifications are purposely written to be ambiguous, it must be a job security thing :-). I agree with your latest comment that the state should be returned. If you look at the issue from a business point of view, a state has a meaning for the user and there can be multiple exist states. It is important to know how a process (a.k.a FSM) ended (e.g. an application to open a bank account that can be accepted or rejected)..

**Comment by jvalkeal** [comment]
@aldib There's a bug in your tests where testLifeCycle() is trying to restory machine persisted in other tests if those tests were run within a same test context. Running just that test succeed, but running all tests made it fail. Adding `@DirtiesContext` fixed that.

```
@DirtiesContext(classMode=ClassMode.AFTER_EACH_TEST_METHOD)
public abstract class AbstractLifeCycleTests implements StatesAndEvents {
```

Thanks for the tests, it really helped fixing bugs. All your tests now pass.
