### ISSUE TITLE
Ability to set UUID for StateMachine

### ISSUE THREAD

**Issue by ouaibsky** [spring-projects/spring-statemachine#241]
We plan to use statemachine (almost an orchestration around RFQ) and it gonna be a nice improvement if we can share same uuid (our Request is already defining an UUID)

Sound pretty simple to implements in statemachine core
* update constructors in AbstractStateMachine by adding uuid  parameter in order to replace 
> 	private UUID uuid = UUID.randomUUID();
* report modification to subclass
* enhance StateMachineFactory by adding getStateMachine with uuid

Of course I can manage to make it compatible with current code.

Do you think it's something that can make sens and on which I can propose a PR ?

Regards
Christophe

**Comment by jvalkeal** [comment]
`UUID` is internal(distributed machines needs to have unique uuid's) and but there is `ID` which is user settable. This change was done in #186.

**Comment by ouaibsky** [comment]
Sure, 
UUID are always unique ... by definition

We plan to use statemachine into  a distributed system (but right now not distribute statemachine itself)
You right we can use id, it's pretty useful when you have an id which is not an UUID (Long, free String, ...)

But when you already get an UUID to identify a unique transaction across a distributed system, it's a little bit painful for monitoring / troubleshouting.

Why ? Because in monitoring trace you'll get 2 uuid: the internal and the one represented into **id**.
You know I'm working for a big company where support team are separate fro developpers, QA ... I know it's not really devops but I have to cope with that.
And with this setup, less you add duplication, making information simple, no reptition better you production and support are.

Christophe

**Comment by jvalkeal** [comment]
Hmm, well you do have a good point about allowing to set UUID now that you explained motivation behind it. Let's try to do it.

**Comment by ouaibsky** [comment]
Before starting, I had a look to the code.
Most important part sounds located at: [AbstractStateMachineFactory.java#L132](https://github.com/spring-projects/spring-statemachine/blob/master/spring-statemachine-core/src/main/java/org/springframework/statemachine/config/AbstractStateMachineFactory.java#L132)

And I feel there is a big requirement when regions are detected: submachine must get a different uuid because there're cached somewhere, am I right ?

I don't really understand which value statemachine will be assigned at line 205 ?

**Comment by jvalkeal** [comment]
We don't care about submachines or regions, at least for now as what is used is a UUID of a root machine. Thought all submachines/regions will get dfferent UUID because of [AbstractStateMachine.java#L107](https://github.com/spring-projects/spring-statemachine/blob/master/spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java#L107). It's still valuable to have different UUID's for submachines/regions when debugging and following logs.

I don't get which class you refer for that line 205 comment.

**Comment by ouaibsky** [comment]
same class: https://github.com/spring-projects/spring-statemachine/blob/master/spring-statemachine-core/src/main/java/org/springframework/statemachine/config/AbstractStateMachineFactory.java#L205

**Comment by jvalkeal** [comment]
Well yes that class is not easiest one to understand as it has evolved overtime and has become a bit clunky. Short story is that JavaDSL/UML will translate into a POJO based config model and from that we build a tree of statedata and use a tree iterator to start building states/machines. Line 205 is where have just built more that one machine having same parents(`initialCount` is probably bad name for variable) so we must have multiple machines for a state so it has to be composition of orthogonal regions. `else` in that `if/else` is just what happens if top-level machine directly contain regions so we need to create a root machine there.
