### ISSUE TITLE
Is it possible to have a transition from any state to another state upon first unaccepted event occurrence?

### ISSUE THREAD

**Issue by ilvisne** [spring-projects/spring-statemachine#371]
Hi,
In our application, we want to disable all actions, if the state can't be determined correctly, while an event is not accepted (the opposite of the deferred events). 

I would like that a transition happens from any (*) state to another, i.e. "unknown", state upon first unaccepted event occurrence. Is this supported?

Thanks.

**Comment by jvalkeal** [comment]
It's difficult to say what you're trying to do as description is quite loose. It might be something what can be modelled with substate where if inner machines doesn't accept any events, that event is then offered to parent machine. This is also model for central error handled so that you don't need to draw transitions from every other state into error handling state. There is no `wildcard` transitions or anything similar.
