### ISSUE TITLE
AbstractStateMachine.getState() returns unexpected value for terminal states

### ISSUE THREAD

**Issue by rgreig** [spring-projects/spring-statemachine#379]
When calling getState() on AbstractStateMachine the behaviour is unexpected where the current state is a terminal state.
The method is defined as follows in the 1.2.x branch currently:
```java
// if we're complete assume we're stopped
// and state was stashed into lastState
synchronized (lock) {
    if (lastState != null && isComplete()) {
        return lastState;
    } else {
        return currentState;
    }
}
```

This means that when the state machine is in a terminal state, it returns the **previous** state. It is not clear to me why someone would want this behaviour, but more seriously it means that when using persistence the wrong value is stored in the StateMachineContext for the current state.
Having thought about this a bit I can see that perhaps a caller may want to be able to know the current state (including pseudo states) and also the most recent non-pseudo state (which I don't think is possible currently?) however the above is not clear in my opinion.

**Comment by jvalkeal** [comment]
This was done explicitly for end states because when machine stops it will null current state(there is no state if machine is stopped) as otherwise it would have been impossible to persist machine with terminal states(machine is terminated when it is reaching end state).

But indeed this feels a bit illogical. Did you found some use cases/code where this behaviour is causing problems?

**Comment by rgreig** [comment]
I have not examined in detail what is happening when the state machine reaches the terminal state - I will do that.

Having said that, I don't immediately see why there should be a relationship between the state machine being stopped or started and its current state? I had intuitively viewed the different between start and stopped being whether events were being processed. Why link state to start/stop? Even if a state machine is force stopped because it is in a terminal state, surely I should still be able to ask the state machine what state it is in?

My use case is that I am modelling human-centric workflows as state machine instances. So you can view a state machine instance as represent a ticket. When a ticket is finally completed (e.g. approved or rejected or whatever that causes it to reach a terminal state) I need that to be persisted - I am using the state machine context as a way of view tickets in different states (i.e. new, in progress, complete). With the current behaviour, when looking at the state machine context in the persistent store it never reaches the terminal state and you cannot distinguish between state machine that are genuinely in a penultimate state from those that are actually in the terminal state.

**Comment by jvalkeal** [comment]
Well, if statemachine is not running then it really can't have any real state. Also we're following uml specs which states that when machine enters terminal state, no further processing in it happens and that's why machine is stopped so that i.e. timers would stop firing. Thought we can argue if machine should keep its current state when machine is stopped as originally I just made a decision to null state when machine stops.

**Comment by jvalkeal** [comment]
Bummer, thought I had tests for restoring end states but couldn't immediately find one. I'll check if it's broken as you just mentioned.

**Comment by rgreig** [comment]
I can definitely see that stopping the state machine when it enters a terminal state makes sense - at that point the state machine can no longer transition etc. But I don't think that it necessary follows that a state machine in a terminal state has **no** state? I have quickly read through the UML spec and I don't see anything that implies that?

There are two specific problems that I can see with treating a state machine that has reached a terminal state:

1. The one you are looking at which means that persistence does not work - restoring a state context effectively resurrects a terminated state machine

2. What if there are multiple terminal states and some part of your app wants to query the state machine to find out which state it reached when it was terminated? Clearly you could do that using other means but that would be cumbersome I think.

Are you saying that any stopped state machine has no state?

**Comment by jvalkeal** [comment]
I was wrong that there's no tests, just didn't found those yesterday. [StateMachinePersistTests.java#L276](https://github.com/spring-projects/spring-statemachine/blob/master/spring-statemachine-core/src/test/java/org/springframework/statemachine/persist/StateMachinePersistTests.java#L276) shows that persistence works with end states.

It's true that state is nulled when machine stops but if state is terminal/end then that is a special case and that state is returned even if machine is stopped. This is what I said that sounds a bit illogical now that you look it a bit closer.

UML spec is quite loose on some parts and leaves a lot of things undefined to get decided by the implementation. I only pointed to it that machine should stop execution when reaching terminal states. Spec doesn't mention anything about whether machine is on state when it is stopped.

**Comment by rgreig** [comment]
Hi Janne,

Sorry for the delay in replying to this!

I was a bit confused initially because after looking at the test and debugging it certainly looked plausible. However I then found the problem - which is how the currentState and lastState get changed when restoring, and crucially when persistence happens when using an interceptor to handle persistence.

If you persist and restore the state machine prior to firing the event to move to the terminal state, plus you are using an interceptor, then the state machine context incorrectly gets the non-terminal state.

It's probably easier just to paste the revised test here (which now fails):
```java
public void testPersistWithEnd() throws Exception {
		context.register(Config8.class);
		context.refresh();
		InMemoryStateMachinePersist1 stateMachinePersist = new InMemoryStateMachinePersist1();
		StateMachinePersister<String, String, String> persister = new DefaultStateMachinePersister<>(stateMachinePersist);
		@SuppressWarnings("unchecked")
		StateMachineFactory<String, String> stateMachineFactory = context.getBean(StateMachineFactory.class);

		StateMachine<String,String> stateMachine = stateMachineFactory.getStateMachine();

		//noinspection unchecked
		stateMachine.getStateMachineAccessor().withRegion().addStateMachineInterceptor(new StateMachineInterceptorAdapter() {

			@Override
			public void postStateChange(State state, Message message, Transition transition, StateMachine stateMachine) {
				try {
					//noinspection unchecked
					persister.persist(stateMachine, "xxx");
				}
				catch (Exception e) {
					fail("Exception persisting state machine: " + e);
				}
			}
		});
		assertThat(stateMachine, notNullValue());
		assertThat(stateMachine.getState().getIds(), containsInAnyOrder("S1"));
		persister.persist(stateMachine, "xxx");
		stateMachine = persister.restore(stateMachine, "xxx");
		stateMachine.sendEvent("E1");
		assertThat(stateMachine.getState().getIds(), containsInAnyOrder("S2"));
		assertThat(stateMachine.isComplete(), is(true));

		// rather than manually calling the persister, this test now uses the interceptor
		//persister.persist(stateMachine, "xxx");

		stateMachine = stateMachineFactory.getStateMachine();
		assertThat(stateMachine.getState().getIds(), containsInAnyOrder("S1"));

		stateMachine = persister.restore(stateMachine, "xxx");
		assertThat(stateMachine.getState().getIds(), containsInAnyOrder("S2"));
		assertThat(stateMachine.isComplete(), is(true));
	}
```

My own thought here is that the currentState/lastState logic is made more complex by the special case of null currentState.

Thanks,
Robert

**Comment by jvalkeal** [comment]
Sorry for delay, I was on PTO.

Thx for that test. Indeed your analysis is correct. I'll try to find a fix for this as well.

**Comment by jvalkeal** [comment]
Dance around currentState/lastState is there for a reason and we really can't get away from it(at least not for now). I'm probably going to move post call to happen after machine is stopped where I think it belongs and which then seem to make this test pass.

```
//		callPostStateChangeInterceptors(toState, message, transition, stateMachine);

		stateMachineExecutor.execute();
		if (isComplete()) {
			stop();
		}
		callPostStateChangeInterceptors(toState, message, transition, stateMachine);
```

**Comment by jvalkeal** [comment]
Closing per https://github.com/spring-projects/spring-statemachine/commit/04f77664b89188ad17f0374913d74f8ae25c964d in 1.2.x

**Comment by irinaalbu89** [comment]
I ran into this error while searching for a solution. How can I persist a StateMachine in the correct final state? The event for state machine stopped is triggered before the lastState is updated. So in the listeners/interceptors, for this event, if I try to persist the state machine, I end up with the lastState (the previous state) being persisted as the current state, instead of the correct current, final state. Any suggestions? Thank you

**Comment by agrison** [comment]
I ran in the exact same problem, it is still not very clear to me why we cannot get the current state via any other API like `getCurrentState()` to simply expose the `currentState` because `getState()` is doing something special when `isComplete()` is `true`.

I am trying to get the current state from within an `@OnStateChanged` annotated method inside a `StateMachineListenerAdapter`, but sadly the current state will be the previous state in case the machine is completed which is not at all what I want since I want to react upon the state change and now I am missing one. It could be fine if I had only one end state but this is not the case, I have multiple.

This is very strange experience as when calling `toString()` on the `StateMachine` it will correctly reflect the current state, but when calling `getState()` it won't.

In my opinion we should have another added API to get the current state without these hoops about the completed status of the machine.

In the end I had to do something like that to have what I wanted while the state machine knows it already as it is stored in its internal `currentState` property:
- if the machine is complete 
  - do not trust `getState()`
  - iterate on all transitions to find the one which is bound to the event in the message payload
  - ensure the target of this transition is a `PseudoStateKind.END`
- otherwise just trust `getState`
 
See below : 

```java
private boolean isTargetEndState(Transition<?, ?> state) {
    var pseudoState = state.getTarget().getPseudoState();
    return pseudoState != null && pseudoState.getKind() == PseudoStateKind.END;
}

@OnStateChanged
public void onStateChanged(@ExtendedStateVariable("...") MyEntity entity,
                           StateMachine<MyStatus, MyAction> stateMachine,
                           Message<MyAction> message) {
    MyStatus newStatus;
    if (stateMachine.isComplete()) {
        newStatus = stateMachine.getTransitions().stream()
                .filter(e -> e.getTrigger().getEvent() == message.getPayload())
                .filter(this::isTargetEndState)
                .map(e -> e.getTarget().getId())
                .findFirst()
                .orElse(MyStatus.INITIATED); // shouldn't happen ;-)
    } else {
        newStatus = stateMachine.getState().getId();
    }

    myEntity.setStatus(newStatus);

    // ....
}
```

Luckily for me I have no state machine where one action can lead to two different targets. In case it is too expensive one can also do it once for all the different payloads and cache it.

Seems to do the trick for the time being on my side, all my tests are green.
