### ISSUE TITLE
Estimated timeline for the GA milestone of 2.0

### ISSUE THREAD

**Issue by cnc-cchou** [spring-projects/spring-statemachine#414]
Is there any estimated timeline for the GA milestone of the spring-statemachine 2.0? I plan to migrate my project to Spring Boot 2.0 once it goes GA in the next couple of months(I'm running at 1.5.7 now), and I'm also considering to adopt this great spring statemachine in the mean time. Will the current 1.2.x code work with the Spring Boot 2.0 or I have to wait for the spring-statemachine 2.0 available?

Thanks.

**Comment by jvalkeal** [comment]
We don't know exactly. Boot is trying to release 2.x around end of this year but it may slip a little. Boot 2.x will have relatively disruptive changes so StateMachine 1.x will not work with it because underlying core from Spring Framework also needs to go to 5.x.

There has been some bigger ideas for StateMachine 2.x like adding some reactive concepts and other conceptual changes but lately I've been thinking that we may need to abandon these changes for 2.0.x serie and do those in 2.1.x. This would allow to release 2.0.0.RELEASE shortly after Boot goes GA.

If there's interest to use StateMachine immediately with Boot 2.x, then I think I need to start planning some milestones releases after next boot milestone release.

**Comment by jvalkeal** [comment]
I've now aligned release plans in milestones. In near future for 2.0.x those are going to follow boot's 2.x schedule. Postponing some further reactor work for 2.1.x.
