### ISSUE TITLE
Wrong documentation regarding proxies?

### ISSUE THREAD

**Issue by vghero** [spring-projects/spring-statemachine#600]
I'm just reading

https://docs.spring.io/spring-statemachine/docs/2.0.3.BUILD-SNAPSHOT/reference/htmlsingle/#statemachine-config-thingstoremember

and wondering if that is true, what is written there :D.

All `guard()` calls mentioned there, are local calls within that class. I don't see a way how a proxy should get between those. AFAIK, proxy calls must always come from the "outside". I'm missing some black magic here :)?

**Comment by jvalkeal** [comment]
This is how `@Configuration` classes and `@Bean` methods in those classes work. You can call `guard1` bean method as it's proxied by spring itself. You're right that normally call needs to come from _outside_ but spring config classes are different.

I believe spring originally did this so that you would not need to autowire those beans in a config class or method level.

**Comment by vghero** [comment]
Ok, lession learned :D! Thanks for clarification and sorry for any inconvenience!
