### ISSUE TITLE
SM persistence and change of configuration

### ISSUE THREAD

**Issue by vghero** [spring-projects/spring-statemachine#605]
I'm starting to play a little bit with this project and took a look at the persisting options it provides.
As far as I understood, it provides e.g. a JPA implementation that simply persists the state as a byte[] via Entity. Now I'm wondering, what happens if there are thousands of states persisted (e.g. for orders) and we have to change transitions and add/change/remove "submachines" by using fork/join etc. That would mean, that the persisted state context in the DB won't fit the current config in code anymore, right? So how are the best practices for updating the old states in the DB with the latest?

Our plan would be, to not persist the whole context, but picking only the exact states and setting them on the Entity as attributes. So we might not have any serialization incompatibilities. But since "submachines" in fork/join, don't seem have something like a "id" to identify them in the configuration, it will be hard to match e.g. 3 states on that order to that SM config in code right? Would it be possible to add some identifier to "submachines" so they can be matched to the states that are persisted?

**Comment by jvalkeal** [comment]
Well yes that would be an issue if you are changing backing configuration for machines and indeed something I thought about when created those samples where you can just go to a database and switch the config. I have had some ideas of introducing some sort of a versioning for configs so that if/when you modify something, then you'd have history of old configs and running machines would not break and new machines could then use newer configs. Something like this would then make things more flexible in terms of not having a need to keep things absolutely compatible(which is a case right now).

It would indeed be appropriate trick to use some sort of id in submachines for later reference and that would help a lot when working with configs and persistence. We kinda have facilities for having random `uuid` for each machine/submachine. There is even `id` but that's mostly used for root machine.

**Comment by jvalkeal** [comment]
Yeah I think it makes sense what you wrote. I could try to see how this might actually look from API's point of view. It's rather big change as it goes in so many places.
