### ISSUE TITLE
current state not set - statemachine.getState() is null

### ISSUE THREAD

**Issue by lkwg82** [spring-projects/spring-statemachine#75]
I used your example from http://projects.spring.io/spring-statemachine/ and tried to get the current state after signals send. 

```java
static class MyApp {

    @Autowired
    StateMachine<States, Events> stateMachine;

    void doSignals() {
        stateMachine.sendEvent(Events.EVENT1);
        System.out.println(stateMachine.getState()); // null
        stateMachine.sendEvent(Events.EVENT2);
    }
}
```

But it is still null. It seems to me like a bug. Did I miss sth?

**Comment by lkwg82** [comment]
Got it. Please add an `stateMachine.start();`  to the example. This will clarify it a bit.

Btw.: Why is the machine not initially started?

**Comment by jvalkeal** [comment]
I'm planning to add a flag to configuration which would start it automatically. It's not started automatically because same classes are also used for substates where lifycycle needs to be handled manually.

Not a difficult job because underlying sm already have a spring Lifcecycle but auto-start is set to false.

**Comment by lkwg82** [comment]
in the meantime adding that missing piece to the example would be sufficient.

**Comment by jvalkeal** [comment]
Project page updated.
