### ISSUE TITLE
Support persisting fork/join with nested regions

### ISSUE THREAD

**Issue by AndreasMaier** [spring-projects/spring-statemachine#94]
I was looking at the persist example which works great to save simple linear state flows so far. Would this also work with parallel fork/join states? I guess you would have to store them somehow into your model and then repopulate that inner state when resetting the state machine? Is that supported/possible?

**Comment by jvalkeal** [comment]
Crap, yes I was hoping to get this somehow fixed before anyone would notice :). Having said that, yes, this is rather complicated topic and indeed you did just catch a flaw in a design. I'm going to change title of this issue to resemble an actual problem mentioned in above. This is probably going to be one of those epic issues.

**Comment by AndreasMaier** [comment]
Thanks for the quick reply. Really like what you are doing here. Nice work, especially on the config interface and the documentation.

**Comment by jvalkeal** [comment]
Naturally I need to somehow identify orthogonal regions in a state machine context(read what you'd persist). Preliminary work for this was done a while back when `StateMachineContext.getChilds()` was added. This wasn't yet fully implemented from end-to-end because I faced some other problems along a way.

My head was kinda spinning trying to thing that how would be persist that potentially infinite recursive structure of nested region states, and more importantly how to restore/reset that state from external storage. As you mentioned simple linear flow is easy but nested regions are very difficult.

This is indeed a good topic of conversation what is actually needed. I think I'm going to try to implement nested regions, but we may need to have a plan B.

**Comment by jvalkeal** [comment]
I probably need slap myself a little about a plan B because I made `org.springframework.statemachine.recipes.tasks.TasksHandler` which already supports nested DAG of tasks. Having said that I guess we really need to find a proper way to persist `TasksHandler` regardless of tasks structure given to it.

I'm glad that there are users who already "catch" these issues because this is one of those you would not just "find out" by looking docs and examples. Good catch indeed mate!

**Comment by jvalkeal** [comment]
Moving this into next release, just don't have enough time for RC1. There's been some work on this but it turned out to be rather complex issue to fix.

**Comment by suraj-bahl-50** [comment]
@jvalkeal: is there a way to store nested (fork/join) state-machine that is initialized with ENUMS. The below link has RepositoryStateMachineModelFactory which only supports string type.

https://docs.spring.io/spring-statemachine/docs/current/reference/#statemachine-examples-datajpamultipersist
